[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
build = "build.rs"
description = "Zero setup cross compilation and cross testing"
documentation = "https://github.com/japaric/cross#cross"
keywords = ["cross", "compilation", "testing", "tool"]
license = "MIT OR Apache-2.0"
name = "cross"
repository = "https://github.com/japaric/cross"
version = "0.1.4-dev"

[dependencies]
error-chain = "0.7.1"
libc = "0.2.18"
rustc_version = "0.1.7"
