[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
build = "build.rs"
description = "Zero setup cross compilation and cross testing"
documentation = "https://github.com/japaric/cross#cross"
keywords = ["cross", "compilation", "testing", "tool"]
license = "MIT OR Apache-2.0"
name = "cross"
repository = "https://github.com/japaric/cross"
version = "0.1.15-dev"

[dependencies]
error-chain = "0.12"
lazy_static = "1.0"
libc = "0.2.18"
rustc_version = "0.2.1"
semver = "0.9.0"
toml = "0.2.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.7", features = ["winbase"] }