[package]
build = "src/build.rs"
description = "Zero setup cross compilation and cross testing"
documentation = "https://github.com/cross-rs/cross"
keywords = ["cross", "compilation", "testing", "tool"]
license = "MIT OR Apache-2.0"
name = "cross"
repository = "https://github.com/cross-rs/cross"
version = "0.2.5"
edition = "2021"
include = [
  "src/**/*",
  "docs/*.md",
  "Cargo.toml",
  "Cargo.lock",
  "LICENSE*",
  "README.md",
  "assets/*",
]
rust-version = "1.64"

[features]
default = []
dev = []

[workspace]
members = ["xtask"]

[dependencies]
is-terminal = "0.4.4"
clap = { version = "4.1", features = ["derive"] }
color-eyre = { version = "0.6.2", default-features = false, features = ["track-caller"] }
eyre = "0.6"
thiserror = "1"
home = "0.5"
rustc_version = "0.4"
toml = "0.5"
which = { version = "4", default_features = false }
shell-escape = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_ignored = "0.1.7"
shell-words = "1.1.0"
const-sha1 = "0.2.0"
ctrlc = { version = "3.2.5", features = ["termination"] }
directories = "4.0.1"
walkdir = { version = "2", optional = true }
tempfile = "3.4.0"
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
semver = "1"

[target.'cfg(not(windows))'.dependencies]
nix = { version = "0.26", default-features = false, features = ["user"] }
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winbase"] }
dunce = "1"

[profile.release]
lto = true

[dev-dependencies]
regex = "1"
once_cell = "1.17"
ignore = "0.4"

[package.metadata.release]
push = false
publish = false
tag = false
pre-release-hook = ["cargo", "xtask", "build-changelog"]
pre-release-commit-message = "release version {{version}}"

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "\\.\\.\\.HEAD"
replace = "...v{{version}}"
exactly = 1

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "<!-- next-url -->"
replace = "<!-- next-url -->\n\n[Unreleased]: https://github.com/cross-rs/{{crate_name}}/compare/v{{version}}...HEAD"
exactly = 1

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }.tar.gz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"
