[package]
documentation = "https://github.com/cross-rs/cross"
license = "MIT OR Apache-2.0"
name = "xtask"
repository = "https://github.com/cross-rs/cross"
version = "0.0.0-dev.0"
edition = "2021"
publish = false


[dependencies]
cross = { path = "..", features = ["dev"] }
walkdir = "2.3.2"
color-eyre = "0.6.1"
eyre = "0.6.8"
clap = { version = "3.2.2", features = ["derive", "env", "unstable-v4"] }
which = { version = "4.2", default_features = false }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
once_cell = "1.12"
